import { ScannerFlags } from "./sfdxCli.types";
/**
 * @description This class is responsible for uploading the SARIF report to the GitHub code scanning API.
 */
export default class SarifUploader {
    private readonly sarifPath;
    private octokit;
    constructor(scannerFlags: ScannerFlags);
    /**
     * @description Uploads the SARIF report generated by other methods to the GitHub code scanning API.
     */
    uploadSarifFileToCodeQL(): Promise<void>;
    /**
     * @description Executes the gzip and base64 commands to compress and encode the SARIF report.
     * @param sarifPath path to the SARIF report.
     */
    private execShellCmds;
}
