/**
 * Types for SARIF 2.1 format - as generated by the sf scanner.
 */
/**
 * @description Represents a single finding in the SARIF output
 */
export interface SarifResult {
    ruleId: string;
    message: {
        text: string;
    };
    locations: {
        physicalLocation: {
            artifactLocation: {
                uri: string;
            };
            region: {
                startLine: number;
                startColumn: number;
                endLine?: number;
                endColumn?: number;
            };
        };
    }[];
}
/**
 * @description Represents a single rule in the SARIF output. Used to correlate the ruleId in the results.
 */
export interface SarifRule {
    id: string;
    shortDescription: {
        text: string;
    };
    helpUri?: string;
    properties: {
        category: string;
        severity: number;
    };
}
/**
 * @description Represents the tool that generated the SARIF output ie: pmd, eslint, etc.
 */
export interface SarifTool {
    driver: {
        name: string;
        rules: SarifRule[];
    };
}
/**
 * @description Represents a single run of the scanner. Contains the tool and the results of the scan.
 */
export interface SarifRun {
    tool: SarifTool;
    results: SarifResult[];
}
/**
 * @description Represents the entire SARIF document. Contains the version and the runs.
 */
export interface SarifDocument {
    version: string;
    runs: SarifRun[];
}
