import * as core from "@actions/core";
import { ScannerFlags } from "./sfdxCli.types.js";
import { Octokit } from "@octokit/action";
import { context } from "@actions/github";
import { fileExists } from "./common.js";
import { spawn } from "node:child_process";

/**
 * @description This class is responsible for uploading the SARIF report to the GitHub code scanning API.
 */
export default class SarifUploader {
  private readonly sarifPath: string;
  private octokit: Octokit;

  constructor(scannerFlags: ScannerFlags) {
    this.sarifPath = scannerFlags.outfile;
    this.octokit = new Octokit();
  }

  /**
   * @description Uploads the SARIF report generated by other methods to the GitHub code scanning API.
   */
  async uploadSarifFileToCodeQL(): Promise<void> {
    console.log("Uploading SARIF report ...");
    try {
      let base64Data = await this.execShellCmds(this.sarifPath);

      const pullRequestNumber = context.payload.pull_request?.number;
      const ref = `refs/pull/${pullRequestNumber}/head`;
      const toolName = "SfScaner";

      if (pullRequestNumber && fileExists(this.sarifPath)) {
        await this.octokit.codeScanning.uploadSarif({
          owner: context.repo.owner,
          repo: context.repo.repo,
          commit_sha: context.sha,
          ref: ref,
          sarif: base64Data,
          tool_name: toolName,
        });

        core.info(
          `SARIF report uploaded successfully for pull request #${pullRequestNumber}`
        );
      } else {
        core.warning("No pull request found. Skipping SARIF upload.");
      }
    } catch (error: any) {
      core.setFailed(`Failed to upload SARIF report: ${error.message}`);
    }
  }

  /**
   * @description Executes the gzip and base64 commands to compress and encode the SARIF report.
   * @param sarifPath path to the SARIF report.
   */
  private async execShellCmds(sarifPath: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const gzipCommand = spawn("gzip", ["-c", sarifPath]);
      const base64Command = spawn("base64", ["-w0"]);

      gzipCommand.stdout.pipe(base64Command.stdin);

      let base64Output = "";

      base64Command.stdout.on("data", (data) => {
        base64Output += data.toString();
      });

      base64Command.on("close", (code) => {
        if (code === 0) {
          resolve(base64Output);
        } else {
          reject(new Error(`Command execution failed with code ${code}`));
        }
      });

      gzipCommand.on("error", (error) => {
        reject(error);
      });

      base64Command.on("error", (error) => {
        reject(error);
      });
    });
  }
}
